import { Injectable } from '@angular/core';

@Injectable()
export class MovieService {

  movies = [
    {year: '2017',
    list: [{name:	'Star Wars: The Last Jedi', boxOfficeRank: 1, awards: ''},
      {name:	'Beauty and the Beast (2017)', boxOfficeRank: 2, awards: ''},
      {name:	'Wonder Woman', boxOfficeRank: 3, awards: ''},
      {name:	'Jumanji: Welcome to the Jungle', boxOfficeRank: 4, awards: ''},
      {name:	'Guardians of the Galaxy Vol. 2', boxOfficeRank: 5, awards: ''},
      {name:	'Spider-Man: Homecoming', boxOfficeRank: 6, awards: ''},
      {name:	'It', boxOfficeRank: 7, awards: ''},
      {name:	'Thor: Ragnarok', boxOfficeRank: 8, awards: ''},
      {name:	'Despicable Me 3', boxOfficeRank: 9, awards: ''},
      {name:	'Justice League', boxOfficeRank: 10, awards: ''},
      {name:	'Logan', boxOfficeRank: 11, awards: ''},
      {name:	'The Fate of the Furious', boxOfficeRank: 12, awards: ''},
      {name:	'Coco', boxOfficeRank: 13, awards: ''},
      {name:	'Dunkirk', boxOfficeRank: 14, awards: 'Best Picture Nominee'},
      {name:	'Get Out', boxOfficeRank: 15, awards: 'Best Picture Nominee'},
      {name:	'The LEGO Batman Movie', boxOfficeRank: 16, awards: ''},
      {name:	'The Boss Baby', boxOfficeRank: 17, awards: ''},
      {name:	'Pirates of the Caribbean: Dead Men Tell No Tales', boxOfficeRank: 18, awards: ''},
      {name:	'Kong: Skull Island', boxOfficeRank: 19, awards: ''},
      {name:	'The Greatest Showman', boxOfficeRank: 20, awards: ''},
      {boxOfficeRank: 39,	name:'The Post',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 48,	name:'The Shape of Water',	awards: 'Best Picture Winner, Best Director'},
      {boxOfficeRank: 51,	name:'Darkest Hour',	awards: 'Best Picture Nominee, Best Actor'},
      {boxOfficeRank: 52,	name:'Three Billboards Outside Ebbing, Missouri',	awards: 'Best Picture Nominee, Best Actress'},
      {boxOfficeRank: 56,	name:'Lady Bird',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 101,	name:'Call Me by Your Name',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 101,	name:'Phantom Thread',	awards: 'Best Picture Nominee'},
    ]},
    {year: '2016',
    list: [{boxOfficeRank: 1,	name:'Rogue One: A Star Wars Story',	awards: ''},
      {boxOfficeRank: 2,	name:'Finding Dory',	awards: ''},
      {boxOfficeRank: 3,	name:'Captain America: Civil War', awards: ''},
      {boxOfficeRank: 4,	name:'The Secret Life of Pets',	awards: ''},
      {boxOfficeRank: 5,	name:'The Jungle Book (2016)',	awards: ''},
      {boxOfficeRank: 6,	name:'Deadpool',	awards: ''},
      {boxOfficeRank: 7,	name:'Zootopia',	awards: ''},
      {boxOfficeRank: 8,	name:'Batman v Superman: Dawn of Justice',awards: ''},
      {boxOfficeRank: 9,	name:'Suicide Squad',awards: ''},
      {boxOfficeRank: 10,	name:'Sing',awards: ''},
      {boxOfficeRank: 11,	name:'Moana',awards: ''},
      {boxOfficeRank: 12,	name:'Fantastic Beasts and Where To Find Them',awards: ''},
      {boxOfficeRank: 13,	name:'Doctor Strange',awards: ''},
      {boxOfficeRank: 14,	name:'Hidden Figures',awards: 'Best Picture Nominee'},
      {boxOfficeRank: 15,	name:'Jason Bourne',	awards: ''},
      {boxOfficeRank: 16,	name:'Star Trek Beyond',	awards: ''},
      {boxOfficeRank: 17,	name:'X-Men: Apocalypse',awards: ''},
      {boxOfficeRank: 18,	name:'Trolls',awards: ''},
      {boxOfficeRank: 19,	name:'La La Land',awards: 'Best Picture Nominee, Best Actress, Best Director'},
      {boxOfficeRank: 20,	name:'Kung Fu Panda 3',	awards: ''},
      {boxOfficeRank: 29,	name:'Arrival',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 46,	name:'Hacksaw Ridge',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 57,	name:'Fences',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 66,	name:'Lion',	awards: 'Best Picture Nominee'},
      {boxOfficeRank: 69,	name:'Manchester by the Sea',	awards: 'Best Picture Nominee, Best Actor'},
      {boxOfficeRank: 92,	name:'Moonlight (2016)',	awards: 'Best Picture Winner'},
      {boxOfficeRank: 95,	name:'Hell or High Water',	awards: 'Best Picture Nominee'}
    ]},
    {year: '2015',
    list: [{boxOfficeRank: 1,	name: 'Star Wars: The Force Awakens', awards: ''},
      {boxOfficeRank: 2,	name: 'Jurassic World', awards: ''},
      {boxOfficeRank: 3,	name: 'Avengers: Age of Ultron', awards: ''},
      {boxOfficeRank: 4,	name: 'Inside Out', awards: ''},
      {boxOfficeRank: 5,	name: 'Furious 7', awards: ''},
      {boxOfficeRank: 6,	name: 'Minions', awards: ''},
      {boxOfficeRank: 7,	name: 'The Hunger Games: Mockingjay - Part 2', awards: ''},
      {boxOfficeRank: 8,	name: 'The Martian', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 9,	name: 'Cinderella (2015)', awards: ''},
      {boxOfficeRank: 10,	name: 'Spectre', awards: ''},
      {boxOfficeRank: 11,	name: 'Mission: Impossible - Rogue Nation', awards: ''},
      {boxOfficeRank: 12,	name: 'Pitch Perfect 2', awards: ''},
      {boxOfficeRank: 13,	name: 'The Revenant', awards: 'Best Picture Nominee, Best Director, Best Actor'},
      {boxOfficeRank: 14,	name: 'Ant-Man', awards: ''},
      {boxOfficeRank: 15,	name: 'Home', awards: ''},
      {boxOfficeRank: 16,	name: 'Hotel Transylvania 2', awards: ''},
      {boxOfficeRank: 17,	name: 'Fifty Shades of Grey', awards: ''},
      {boxOfficeRank: 18,	name: 'The SpongeBob Movie: Sponge Out of Water', awards: ''},
      {boxOfficeRank: 19,	name: 'Straight Outta Compton', awards: ''},
      {boxOfficeRank: 20,	name: 'San Andreas', awards: ''},
      {boxOfficeRank: 21,	name: 'Mad Max: Fury Road', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 42,	name: 'Bridge of Spies', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 44,	name: 'The Big Short', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 62,	name: 'Spotlight', awards: 'Best Picture Winner'},
      {boxOfficeRank: 70,	name: 'Brooklyn', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 101,	name: 'Room', awards: 'Best Picture Nominee, Best Actress'}
    ]},
    {
      year: '2014',
      list: [
        {boxOfficeRank: 1,	name: 'American Sniper', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 2,	name: 'The Hunger Games: Mockingjay - Part 1', awards: ''},
        {boxOfficeRank: 3,	name: 'Guardians of the Galaxy', awards: ''},
        {boxOfficeRank: 4,	name: 'Captain America: The Winter Soldier', awards: ''},
        {boxOfficeRank: 5,	name: 'The LEGO Movie', awards: ''},
        {boxOfficeRank: 6,	name: 'The Hobbit: The Battle of the Five Armies', awards: ''},
        {boxOfficeRank: 7,	name: 'Transformers: Age of Extinction', awards: ''},
        {boxOfficeRank: 8,	name: 'Maleficent', awards: ''},
        {boxOfficeRank: 9,	name: 'X-Men: Days of Future Past', awards: ''},
        {boxOfficeRank: 10,	name: 'Big Hero 6', awards: ''},
        {boxOfficeRank: 11,	name: 'Dawn of the Planet of the Apes', awards: ''},
        {boxOfficeRank: 12,	name: 'The Amazing Spider-Man 2', awards: ''},
        {boxOfficeRank: 13,	name: 'Godzilla (2014)', awards: ''},
        {boxOfficeRank: 14,	name: '22 Jump Street', awards: ''},
        {boxOfficeRank: 15,	name: 'Teenage Mutant Ninja Turtles (2014)', awards: ''},
        {boxOfficeRank: 16,	name: 'Interstellar', awards: ''},
        {boxOfficeRank: 17,	name: 'How to Train Your Dragon 2', awards: ''},
        {boxOfficeRank: 18,	name: 'Gone Girl', awards: ''},
        {boxOfficeRank: 19,	name: 'Divergent', awards: ''},
        {boxOfficeRank: 20,	name: 'Neighbors', awards: ''},
        {boxOfficeRank: 36,	name: 'The Imitation Game', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 54,	name: 'The Grand Budapest Hotel', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 61,	name: 'Selma', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 78,	name: 'Birdman', awards: 'Best Picture Winner, Best Director'},
        {boxOfficeRank: 85,	name: 'The Theory of Everything', awards: 'Best Picture Nominee, Best Actor'},
        {boxOfficeRank: 100,	name: 'Boyhood', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'Whiplash', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'Still Alice', awards: 'Best Actress'}
      ]
    },
    {
      year: '2013',
      list: [
        {boxOfficeRank: 1,	name: 'The Hunger Games: Catching Fire', awards: ''},
        {boxOfficeRank: 2,	name: 'Iron Man 3', awards: ''},
        {boxOfficeRank: 3,	name: 'Frozen', awards: ''},
        {boxOfficeRank: 4,	name: 'Despicable Me 2', awards: ''},
        {boxOfficeRank: 5,	name: 'Man of Steel', awards: ''},
        {boxOfficeRank: 6,	name: 'Gravity', awards: 'Best Picture Nominee, Best Director'},
        {boxOfficeRank: 7,	name: 'Monsters University', awards: ''},
        {boxOfficeRank: 8,	name: 'The Hobbit: The Desolation of Smaug', awards: ''},
        {boxOfficeRank: 9,	name: 'Fast & Furious 6', awards: ''},
        {boxOfficeRank: 10,	name: 'Oz The Great and Powerful', awards: ''},
        {boxOfficeRank: 11,	name: 'Star Trek Into Darkness', awards: ''},
        {boxOfficeRank: 12,	name: 'Thor: The Dark World', awards: ''},
        {boxOfficeRank: 13,	name: 'World War Z', awards: ''},
        {boxOfficeRank: 14,	name: 'The Croods', awards: ''},
        {boxOfficeRank: 15,	name: 'The Heat', awards: ''},
        {boxOfficeRank: 16,	name: 'We\'re the Millers', awards: ''},
        {boxOfficeRank: 17,	name: 'American Hustle', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 18,	name: 'The Great Gatsby', awards: ''},
        {boxOfficeRank: 19,	name: 'The Conjuring', awards: ''},
        {boxOfficeRank: 20,	name: 'Identity Thief', awards: ''},
        {boxOfficeRank: 28,	name: 'The Wolf of Wall Street', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 32,	name: 'Captain Phillips', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 62,	name: '12 Years a Slave', awards: 'Best Picture Winner'},
        {boxOfficeRank: 80,	name: 'Philomena', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 86,	name: 'Blue Jasmine', awards: 'Best Actress'},
        {boxOfficeRank: 95,	name: 'Dallas Buyers Club', awards: 'Best Picture Nominee, Best Actor'},
        {boxOfficeRank: 100,	name: 'Her', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'Nebraska', awards: 'Best Picture Nominee'},
      ]
    },
    {year: '2012',
    list: [
      {boxOfficeRank: 1,	name: 'Marvel\'s The Avengers', awards: ''},
      {boxOfficeRank: 2,	name: 'The Dark Knight Rises', awards: ''},
      {boxOfficeRank: 3,	name: 'The Hunger Games', awards: ''},
      {boxOfficeRank: 4,	name: 'Skyfall', awards: ''},
      {boxOfficeRank: 5,	name: 'The Hobbit: An Unexpected Journey', awards: ''},
      {boxOfficeRank: 6,	name: 'The Twilight Saga: Breaking Dawn Part 2', awards: ''},
      {boxOfficeRank: 7,	name: 'The Amazing Spider-Man', awards: ''},
      {boxOfficeRank: 8,	name: 'Brave', awards: ''},
      {boxOfficeRank: 9,	name: 'Ted', awards: ''},
      {boxOfficeRank: 10,	name: 'Madagascar 3: Europe\'s Most Wanted', awards: ''},
      {boxOfficeRank: 11,	name: 'Dr. Seuss\' The Lorax', awards: ''},
      {boxOfficeRank: 12,	name: 'Wreck-It Ralph', awards: ''},
      {boxOfficeRank: 13,	name: 'Lincoln', awards: 'Best Picture Nominee, Best Actor'},
      {boxOfficeRank: 14,	name: 'MIB 3', awards: ''},
      {boxOfficeRank: 15,	name: 'Django Unchained', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 16,	name: 'Ice Age: Continental Drift', awards: ''},
      {boxOfficeRank: 17,	name: 'Snow White and the Huntsman', awards: ''},
      {boxOfficeRank: 18,	name: 'Les Miserables (2012)', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 19,	name: 'Hotel Transylvania', awards: ''},
      {boxOfficeRank: 20,	name: 'Taken 2', awards: ''},
      {boxOfficeRank: 22,	name: 'Argo', awards: 'Best Picture Winner'},
      {boxOfficeRank: 23,	name: 'Silver Linings Playbook', awards: 'Best Picture Nominee, Best Actress'},
      {boxOfficeRank: 27,	name: 'Life of Pi', awards: 'Best Director'},
      {boxOfficeRank: 32,	name: 'Zero Dark Thirty', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 101,	name: 'Amour', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 101,	name: 'Beasts of the Southern Wild', awards: 'Best Picture Nominee'}
    ]},
    {
      year: '2011',
      list: [
        {boxOfficeRank: 1,	name: 'Harry Potter and the Deathly Hallows Part 2', awards: ''},
        {boxOfficeRank: 2,	name: 'Transformers: Dark of the Moon', awards: ''},
        {boxOfficeRank: 3,	name: 'The Twilight Saga: Breaking Dawn Part 1', awards: ''},
        {boxOfficeRank: 4,	name: 'The Hangover Part II', awards: ''},
        {boxOfficeRank: 5,	name: 'Pirates of the Caribbean: On Stranger Tides', awards: ''},
        {boxOfficeRank: 6,	name: 'Fast Five', awards: ''},
        {boxOfficeRank: 7,	name: 'Mission: Impossible - Ghost Protocol', awards: ''},
        {boxOfficeRank: 8,	name: 'Cars 2', awards: ''},
        {boxOfficeRank: 9,	name: 'Sherlock Holmes: A Game of Shadows', awards: ''},
        {boxOfficeRank: 10,	name: 'Thor', awards: ''},
        {boxOfficeRank: 11,	name: 'Rise of the Planet of the Apes', awards: ''},
        {boxOfficeRank: 12,	name: 'Captain America: The First Avenger', awards: ''},
        {boxOfficeRank: 13,	name: 'The Help', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 14,	name: 'Bridesmaids', awards: ''},
        {boxOfficeRank: 15,	name: 'Kung Fu Panda 2', awards: ''},
        {boxOfficeRank: 16,	name: 'Puss in Boots', awards: ''},
        {boxOfficeRank: 17,	name: 'X-Men: First Class', awards: ''},
        {boxOfficeRank: 18,	name: 'Rio', awards: ''},
        {boxOfficeRank: 19,	name: 'The Smurfs', awards: ''},
        {boxOfficeRank: 20,	name: 'Alvin and the Chipmunks: Chipwrecked', awards: ''},
        {boxOfficeRank: 39,	name: 'The Descendants', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 41,	name: 'War Horse', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 47,	name: 'Moneyball', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 49,	name: 'Hugo', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 59,	name: 'Midnight in Paris', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 71,	name: 'The Artist', awards: 'Best Picture Winner, Best Director, Best Actor'},
        {boxOfficeRank: 97,	name: 'Extremely Loud & Incredibly Close', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 100,	name: 'The Iron Lady', awards: 'Best Actress'},
        {boxOfficeRank: 101,	name: 'The Tree of Life', awards: 'Best Picture Nominee'},
      ]
    },
    {
      year: '2010',
      list: [
        {boxOfficeRank: 1,	name: 'Toy Story 3', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 2,	name: 'Alice in Wonderland (2010)', awards: ''},
        {boxOfficeRank: 3,	name: 'Iron Man 2', awards: ''},
        {boxOfficeRank: 4,	name: 'The Twilight Saga: Eclipse', awards: ''},
        {boxOfficeRank: 5,	name: 'Harry Potter and the Deathly Hallows Part 1', awards: ''},
        {boxOfficeRank: 6,	name: 'Inception', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 7,	name: 'Despicable Me', awards: ''},
        {boxOfficeRank: 8,	name: 'Shrek Forever After', awards: ''},
        {boxOfficeRank: 9,	name: 'How to Train Your Dragon', awards: ''},
        {boxOfficeRank: 10,	name: 'Tangled', awards: ''},
        {boxOfficeRank: 11,	name: 'The Karate Kid', awards: ''},
        {boxOfficeRank: 12,	name: 'Tron Legacy', awards: ''},
        {boxOfficeRank: 13,	name: 'True Grit', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 14,	name: 'Clash of the Titans (2010)', awards: ''},
        {boxOfficeRank: 15,	name: 'Grown Ups', awards: ''},
        {boxOfficeRank: 16,	name: 'Little Fockers', awards: ''},
        {boxOfficeRank: 17,	name: 'Megamind', awards: ''},
        {boxOfficeRank: 18,	name: 'The King\'s Speech', awards: 'Best Picture Winner, Best Director, Best Actor'},
        {boxOfficeRank: 19,	name: 'The Last Airbender', awards: ''},
        {boxOfficeRank: 20,	name: 'Shutter Island', awards: ''},
        {boxOfficeRank: 25,	name: 'Black Swan', awards: 'Best Picture Nominee, Best Actress'},
        {boxOfficeRank: 32,	name: 'The Social Network', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 35,	name: 'The Fighter', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: '127 Hours', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'The Kids Are All Right', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'Winter\'s Bone', awards: 'Best Picture Nominee'},
      ]
    },
    {
      year: '2009',
      list: [
        {boxOfficeRank:1,	name: 'Avatar', awards: 'Best Picture Nominee'},
        {boxOfficeRank:2,	name: 'Transformers: Revenge of the Fallen', awards: ''},
        {boxOfficeRank:3,	name: 'Harry Potter and the Half-Blood Prince', awards: ''},
        {boxOfficeRank:4,	name: 'The Twilight Saga: New Moon', awards: ''},
        {boxOfficeRank:5,	name: 'Up', awards: 'Best Picture Nominee'},
        {boxOfficeRank:6,	name: 'The Hangover', awards: ''},
        {boxOfficeRank:7,	name: 'Star Trek', awards: ''},
        {boxOfficeRank:8,	name: 'The Blind Side', awards: 'Best Picture Nominee, Best Actress'},
        {boxOfficeRank:9,	name: 'Alvin and the Chipmunks: The Squeakquel', awards: ''},
        {boxOfficeRank:10,	name: 'Sherlock Holmes', awards: ''},
        {boxOfficeRank:11,	name: 'Monsters Vs. Aliens', awards: ''},
        {boxOfficeRank:12,	name: 'Ice Age: Dawn of the Dinosaurs', awards: ''},
        {boxOfficeRank:13,	name: 'X-Men Origins: Wolverine', awards: ''},
        {boxOfficeRank:14,	name: 'Night at the Museum: Battle of the Smithsonian', awards: ''},
        {boxOfficeRank:15,	name: '2012', awards: ''},
        {boxOfficeRank:16,	name: 'The Proposal', awards: ''},
        {boxOfficeRank:17,	name: 'Fast and Furious', awards: ''},
        {boxOfficeRank:18,	name: 'G.I. Joe: The Rise of Cobra', awards: ''},
        {boxOfficeRank:19,	name: 'Paul Blart: Mall Cop', awards: ''},
        {boxOfficeRank:20,	name: 'Taken', awards: ''},
        {boxOfficeRank:25,	name: 'Inglourious Basterds', awards: 'Best Picture Nominee'},
        {boxOfficeRank:27,	name: 'District 9', awards: 'Best Picture Nominee'},
        {boxOfficeRank:38,	name: 'Up in the Air', awards: 'Best Picture Nominee'},
        {boxOfficeRank:65,	name: 'Precious: Based on the Novel "Push" by Sapphire', awards: 'Best Picture Nominee'},
        {boxOfficeRank:75,	name: 'Crazy Heart', awards: 'Best Actor'},
        {boxOfficeRank:101,	name: 'A Serious Man', awards: 'Best Picture Nominee'},
        {boxOfficeRank:101,	name: 'An Education', awards: 'Best Picture Nominee'},
        {boxOfficeRank:101,	name: 'The Hurt Locker', awards: 'Best Picture Winner, Best Director'}
      ]
    },
    {year: '2008',
    list: [
      {boxOfficeRank: 1,	name: 'The Dark Knight', awards: ''},
      {boxOfficeRank: 2,	name: 'Iron Man', awards: ''},
      {boxOfficeRank: 3,	name: 'Indiana Jones and the Kingdom of the Crystal Skull', awards: ''},
      {boxOfficeRank: 4,	name: 'Hancock', awards: ''},
      {boxOfficeRank: 5,	name: 'WALL-E', awards: ''},
      {boxOfficeRank: 6,	name: 'Kung Fu Panda', awards: ''},
      {boxOfficeRank: 7,	name: 'Twilight', awards: ''},
      {boxOfficeRank: 8,	name: 'Madagascar: Escape 2 Africa', awards: ''},
      {boxOfficeRank: 9,	name: 'Quantum of Solace', awards: ''},
      {boxOfficeRank: 10,	name: 'Dr. Seuss\' Horton Hears a Who!', awards: ''},
      {boxOfficeRank: 11,	name: 'Sex and the City', awards: ''},
      {boxOfficeRank: 12,	name: 'Gran Torino', awards: ''},
      {boxOfficeRank: 13,	name: 'Mamma Mia!', awards: ''},
      {boxOfficeRank: 14,	name: 'Marley and Me', awards: ''},
      {boxOfficeRank: 15,	name: 'The Chronicles of Narnia: Prince Caspian', awards: ''},
      {boxOfficeRank: 16,	name: 'Slumdog Millionaire', awards: 'Best Picture Winner, Best Director'},
      {boxOfficeRank: 17,	name: 'The Incredible Hulk', awards: ''},
      {boxOfficeRank: 18,	name: 'Wanted', awards: ''},
      {boxOfficeRank: 19,	name: 'Get Smart', awards: ''},
      {boxOfficeRank: 20,	name: 'The Curious Case of Benjamin Button', awards: 'Best Picture Nominee'},
      {boxOfficeRank: 82,	name: 'The Reader', awards: 'Best Picture Nominee, Best Actress'},
      {boxOfficeRank: 89,	name: 'Milk', awards: 'Best Picture Nominee, Best Actor'},
      {boxOfficeRank: 101,	name: 'Frost/Nixon', awards: 'Best Picture Nominee'}
    ]},
    {
      year: '2007',
      list: [
        {boxOfficeRank: 1,	name: 'Spider-Man 3', awards: ''},
        {boxOfficeRank: 2,	name: 'Shrek the Third', awards: ''},
        {boxOfficeRank: 3,	name: 'Transformers', awards: ''},
        {boxOfficeRank: 4,	name: 'Pirates of the Caribbean: At World\'s End', awards: ''},
        {boxOfficeRank: 5,	name: 'Harry Potter and the Order of the Phoenix', awards: ''},
        {boxOfficeRank: 6,	name: 'I Am Legend', awards: ''},
        {boxOfficeRank: 7,	name: 'The Bourne Ultimatum', awards: ''},
        {boxOfficeRank: 8,	name: 'National Treasure: Book of Secrets', awards: ''},
        {boxOfficeRank: 9,	name: 'Alvin and the Chipmunks', awards: ''},
        {boxOfficeRank: 10,	name: '300', awards: ''},
        {boxOfficeRank: 11,	name: 'Ratatouille', awards: ''},
        {boxOfficeRank: 12,	name: 'The Simpsons Movie', awards: ''},
        {boxOfficeRank: 13,	name: 'Wild Hogs', awards: ''},
        {boxOfficeRank: 14,	name: 'Knocked Up', awards: ''},
        {boxOfficeRank: 15,	name: 'Juno', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 16,	name: 'Rush Hour 3', awards: ''},
        {boxOfficeRank: 17,	name: 'Live Free or Die Hard', awards: ''},
        {boxOfficeRank: 18,	name: 'Fantastic Four: Rise of the Silver Surfer', awards: ''},
        {boxOfficeRank: 19,	name: 'American Gangster', awards: ''},
        {boxOfficeRank: 20,	name: 'Enchanted', awards: ''},
        {boxOfficeRank: 36,	name: 'No Country for Old Men', awards: 'Best Picture Winner, Best Director'},
        {boxOfficeRank: 50,	name: 'Atonement', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 55,	name: 'Michael Clayton', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 66,	name: 'There Will Be Blood', awards: 'Best Picture Nominee, Best Actor'},
        {boxOfficeRank: 101,	name: 'La Vie En Rose', awards: 'Best Actress'}
      ]
    },
    {
      year: '2006',
      list: [
        {boxOfficeRank: 1,	name: 'Pirates of the Caribbean: Dead Man\'s Chest', awards: ''},
        {boxOfficeRank: 2,	name: 'Night at the Museum', awards: ''},
        {boxOfficeRank: 3,	name: 'Cars', awards: ''},
        {boxOfficeRank: 4,	name: 'X-Men: The Last Stand', awards: ''},
        {boxOfficeRank: 5,	name: 'The Da Vinci Code', awards: ''},
        {boxOfficeRank: 6,	name: 'Superman Returns', awards: ''},
        {boxOfficeRank: 7,	name: 'Happy Feet', awards: ''},
        {boxOfficeRank: 8,	name: 'Ice Age: The Meltdown', awards: ''},
        {boxOfficeRank: 9,	name: 'Casino Royale', awards: ''},
        {boxOfficeRank: 10,	name: 'The Pursuit of Happyness', awards: ''},
        {boxOfficeRank: 11,	name: 'Over the Hedge', awards: ''},
        {boxOfficeRank: 12,	name: 'Talladega Nights: The Ballad of Ricky Bobby', awards: ''},
        {boxOfficeRank: 13,	name: 'Click', awards: ''},
        {boxOfficeRank: 14,	name: 'Mission: Impossible III', awards: ''},
        {boxOfficeRank: 15,	name: 'The Departed', awards: 'Best Picture, Best Director'},
        {boxOfficeRank: 16,	name: 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan', awards: ''},
        {boxOfficeRank: 17,	name: 'The Devil Wears Prada', awards: ''},
        {boxOfficeRank: 18,	name: 'The Break-Up', awards: ''},
        {boxOfficeRank: 19,	name: 'Dreamgirls', awards: ''},
        {boxOfficeRank: 20,	name: 'Scary Movie 4', awards: ''},
        {boxOfficeRank: 51,	name: 'Little Miss Sunshine', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 57,	name: 'The Queen', awards: 'Best Picture Nominee, Best Actress'},
        {boxOfficeRank: 92,	name: 'Babel', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'Letters from Iwo Jima', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 101,	name: 'The Last King of Scotland', awards: 'Best Actor'}
      ]
    },
    {
      year: '2005',
      list: [
        {boxOfficeRank: 1,	name: 'Star Wars: Episode III - Revenge of the Sith', awards: ''},
        {boxOfficeRank: 2,	name: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', awards: ''},
        {boxOfficeRank: 3,	name: 'Harry Potter and the Goblet of Fire', awards: ''},
        {boxOfficeRank: 4,	name: 'War of the Worlds', awards: ''},
        {boxOfficeRank: 5,	name: 'King Kong', awards: ''},
        {boxOfficeRank: 6,	name: 'Wedding Crashers', awards: ''},
        {boxOfficeRank: 7,	name: 'Charlie and the Chocolate Factory', awards: ''},
        {boxOfficeRank: 8,	name: 'Batman Begins', awards: ''},
        {boxOfficeRank: 9,	name: 'Madagascar', awards: ''},
        {boxOfficeRank: 10,	name: 'Mr. & Mrs. Smith', awards: ''},
        {boxOfficeRank: 11,	name: 'Hitch', awards: ''},
        {boxOfficeRank: 12,	name: 'The Longest Yard', awards: ''},
        {boxOfficeRank: 13,	name: 'Fantastic Four (2005)', awards: ''},
        {boxOfficeRank: 14,	name: 'Chicken Little', awards: ''},
        {boxOfficeRank: 15,	name: 'Robots', awards: ''},
        {boxOfficeRank: 16,	name: 'Walk the Line', awards: 'Best Actress'},
        {boxOfficeRank: 17,	name: 'The Pacifier', awards: ''},
        {boxOfficeRank: 18,	name: 'Fun with Dick and Jane', awards: ''},
        {boxOfficeRank: 19,	name: 'The 40-Year-Old Virgin', awards: ''},
        {boxOfficeRank: 20,	name: 'Flightplan', awards: ''},
        {boxOfficeRank: 22,	name: 'Brokeback Mountain', awards: 'Best Picture Nominee, Best Director'},
        {boxOfficeRank: 49,	name: 'Crash', awards: 'Best Picture Winner'},
        {boxOfficeRank: 62,	name: 'Munich', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 89,	name: 'Good Night, and Good Luck.', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 95,	name: 'Capote', awards: 'Best Picture Nominee, Best Actor'}
      ]
    },
    {
      year: '2004',
      list: [
        {boxOfficeRank: 1,	name: 'Shrek 2', awards: ''},
        {boxOfficeRank: 2,	name: 'Spider-Man 2', awards: ''},
        {boxOfficeRank: 3,	name: 'The Passion of the Christ', awards: ''},
        {boxOfficeRank: 4,	name: 'Meet the Fockers', awards: ''},
        {boxOfficeRank: 5,	name: 'The Incredibles', awards: ''},
        {boxOfficeRank: 6,	name: 'Harry Potter and the Prisoner of Azkaban', awards: ''},
        {boxOfficeRank: 7,	name: 'The Day After Tomorrow', awards: ''},
        {boxOfficeRank: 8,	name: 'The Bourne Supremacy', awards: ''},
        {boxOfficeRank: 9,	name: 'National Treasure', awards: ''},
        {boxOfficeRank: 10,	name: 'The Polar Express', awards: ''},
        {boxOfficeRank: 11,	name: 'Shark Tale', awards: ''},
        {boxOfficeRank: 12,	name: 'I, Robot', awards: ''},
        {boxOfficeRank: 13,	name: 'Troy', awards: ''},
        {boxOfficeRank: 14,	name: 'Ocean\'s Twelve', awards: ''},
        {boxOfficeRank: 15,	name: '50 First Dates', awards: ''},
        {boxOfficeRank: 16,	name: 'Van Helsing', awards: ''},
        {boxOfficeRank: 17,	name: 'Fahrenheit 9/11', awards: ''},
        {boxOfficeRank: 18,	name: 'Lemony Snicket\'s A Series of Unfortunate Events', awards: ''},
        {boxOfficeRank: 19,	name: 'DodgeBall: A True Underdog Story', awards: ''},
        {boxOfficeRank: 20,	name: 'The Village', awards: ''},
        {boxOfficeRank: 22,	name: 'The Aviator', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 24,	name: 'Million Dollar Baby', awards: 'Best Picture Winner, Best Actress, Best Director'},
        {boxOfficeRank: 37,	name: 'Ray', awards: 'Best Picture Nominee, Best Actor'},
        {boxOfficeRank: 40,	name: 'Sideways', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 61,	name: 'Finding Neverland', awards: 'Best Picture Nominee'}
      ]
    },
    {
      year: '2003',
      list: [
        {boxOfficeRank: 1,	name: 'The Lord of the Rings: The Return of the King', awards: 'Best Picture Winner, Best Director'},
        {boxOfficeRank: 2,	name: 'Finding Nemo', awards: ''},
        {boxOfficeRank: 3,	name: 'Pirates of the Caribbean: The Curse of the Black Pearl', awards: ''},
        {boxOfficeRank: 4,	name: 'The Matrix Reloaded', awards: ''},
        {boxOfficeRank: 5,	name: 'Bruce Almighty', awards: ''},
        {boxOfficeRank: 6,	name: 'X2: X-Men United', awards: ''},
        {boxOfficeRank: 7,	name: 'Elf', awards: ''},
        {boxOfficeRank: 8,	name: 'Terminator 3: Rise of the Machines', awards: ''},
        {boxOfficeRank: 9,	name: 'The Matrix Revolutions', awards: ''},
        {boxOfficeRank: 10,	name: 'Cheaper by the Dozen', awards: ''},
        {boxOfficeRank: 11,	name: 'Bad Boys II', awards: ''},
        {boxOfficeRank: 12,	name: 'Anger Management', awards: ''},
        {boxOfficeRank: 13,	name: 'Bringing Down the House', awards: ''},
        {boxOfficeRank: 14,	name: 'Hulk', awards: ''},
        {boxOfficeRank: 15,	name: '2 Fast 2 Furious', awards: ''},
        {boxOfficeRank: 16,	name: 'Something\'s Gotta Give', awards: ''},
        {boxOfficeRank: 17,	name: 'Seabiscuit', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 18,	name: 'S.W.A.T.', awards: ''},
        {boxOfficeRank: 19,	name: 'Spy Kids 3D: Game Over', awards: ''},
        {boxOfficeRank: 20,	name: 'The Last Samurai', awards: ''},
        {boxOfficeRank: 31,	name: 'Master and Commander: The Far Side of the World', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 33,	name: 'Mystic River', awards: 'Best Picture Nominee, Best Actor'},
        {boxOfficeRank: 67,	name: 'Lost in Translation', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 83,	name: 'Monster', awards: 'Best Actress'}
      ]
    },
    {
      year: '2002',
      list: [
        {boxOfficeRank: 1,	name: 'Spider-Man', awards: ''},
        {boxOfficeRank: 2,	name: 'The Lord of the Rings: The Two Towers', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 3,	name: 'Star Wars: Episode II - Attack of the Clones', awards: ''},
        {boxOfficeRank: 4,	name: 'Harry Potter and the Chamber of Secrets', awards: ''},
        {boxOfficeRank: 5,	name: 'My Big Fat Greek Wedding', awards: ''},
        {boxOfficeRank: 6,	name: 'Signs', awards: ''},
        {boxOfficeRank: 7,	name: 'Austin Powers in Goldmember', awards: ''},
        {boxOfficeRank: 8,	name: 'Men in Black II', awards: ''},
        {boxOfficeRank: 9,	name: 'Ice Age', awards: ''},
        {boxOfficeRank: 10,	name: 'Chicago', awards: 'Best Picture Winner'},
        {boxOfficeRank: 11,	name: 'Catch Me If You Can', awards: ''},
        {boxOfficeRank: 12,	name: 'Die Another Day', awards: ''},
        {boxOfficeRank: 13,	name: 'Scooby-Doo', awards: ''},
        {boxOfficeRank: 14,	name: 'Lilo & Stitch', awards: ''},
        {boxOfficeRank: 15,	name: 'XXX', awards: ''},
        {boxOfficeRank: 16,	name: 'The Santa Clause 2', awards: ''},
        {boxOfficeRank: 17,	name: 'Minority Report', awards: ''},
        {boxOfficeRank: 18,	name: 'The Ring', awards: ''},
        {boxOfficeRank: 19,	name: 'Sweet Home Alabama', awards: ''},
        {boxOfficeRank: 20,	name: 'Mr. Deeds', awards: ''},
        {boxOfficeRank: 35,	name: 'Gangs of New York', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 56,	name: 'The Hours', awards: 'Best Picture Nominee, Best Actress'},
        {boxOfficeRank: 80,	name: 'The Pianist', awards: 'Best Picture Nominee, Best Director, Best Actor'}
      ]
    },
    {
      year: '2001',
      list: [
        {boxOfficeRank: 1,	name: 'Harry Potter and the Sorcerer\'s Stone', awards: ''},
        {boxOfficeRank: 2,	name: 'The Lord of the Rings: The Fellowship of the Ring', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 3,	name: 'Shrek', awards: ''},
        {boxOfficeRank: 4,	name: 'Monsters, Inc.', awards: ''},
        {boxOfficeRank: 5,	name: 'Rush Hour 2', awards: ''},
        {boxOfficeRank: 6,	name: 'The Mummy Returns', awards: ''},
        {boxOfficeRank: 7,	name: 'Pearl Harbor', awards: ''},
        {boxOfficeRank: 8,	name: 'Ocean\'s Eleven', awards: ''},
        {boxOfficeRank: 9,	name: 'Jurassic Park III', awards: ''},
        {boxOfficeRank: 10,	name: 'Planet of the Apes (2001)', awards: ''},
        {boxOfficeRank: 11,	name: 'A Beautiful Mind', awards: 'Best Picture Winner, Best Director'},
        {boxOfficeRank: 12,	name: 'Hannibal', awards: ''},
        {boxOfficeRank: 13,	name: 'American Pie 2', awards: ''},
        {boxOfficeRank: 14,	name: 'The Fast and the Furious', awards: ''},
        {boxOfficeRank: 15,	name: 'Lara Croft: Tomb Raider', awards: ''},
        {boxOfficeRank: 16,	name: 'Dr. Dolittle 2', awards: ''},
        {boxOfficeRank: 17,	name: 'Spy Kids', awards: ''},
        {boxOfficeRank: 18,	name: 'Black Hawk Down', awards: ''},
        {boxOfficeRank: 19,	name: 'The Princess Diaries', awards: ''},
        {boxOfficeRank: 20,	name: 'Vanilla Sky', awards: ''},
        {boxOfficeRank: 29,	name: 'Training Day', awards: 'Best Actor'},
        {boxOfficeRank: 43,	name: 'Moulin Rouge!', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 59,	name: 'Gosford Park', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 68,	name: 'In the Bedroom', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 76,	name: 'Monster\'s Ball', awards: 'Best Actress'}
      ]
    },
    {
      year: '2000',
      list: [
        {boxOfficeRank: 1,	name: 'How the Grinch Stole Christmas', awards: ''},
        {boxOfficeRank: 2,	name: 'Cast Away', awards: ''},
        {boxOfficeRank: 3,	name: 'Mission: Impossible II', awards: ''},
        {boxOfficeRank: 4,	name: 'Gladiator', awards: 'Best Picture Winner, Best Actor'},
        {boxOfficeRank: 5,	name: 'What Women Want', awards: ''},
        {boxOfficeRank: 6,	name: 'The Perfect Storm', awards: ''},
        {boxOfficeRank: 7,	name: 'Meet the Parents', awards: ''},
        {boxOfficeRank: 8,	name: 'X-Men', awards: ''},
        {boxOfficeRank: 9,	name: 'Scary Movie', awards: ''},
        {boxOfficeRank: 10,	name: 'What Lies Beneath', awards: ''},
        {boxOfficeRank: 11,	name: 'Dinosaur', awards: ''},
        {boxOfficeRank: 12,	name: 'Crouching Tiger, Hidden Dragon', awards: 'Best Picture Nominee'},
        {boxOfficeRank: 13,	name: 'Erin Brockovich', awards: 'Best Picture Nominee, Best Actress'},
        {boxOfficeRank: 14,	name: 'Charlie\'s Angels', awards: ''},
        {boxOfficeRank: 15,	name: 'Traffic', awards: 'Best Picture Nominee, Best Director'},
        {boxOfficeRank: 16,	name: 'The Nutty Professor II: The Klumps', awards: ''},
        {boxOfficeRank: 17,	name: 'Big Momma\'s House', awards: ''},
        {boxOfficeRank: 18,	name: 'Remember the Titans', awards: ''},
        {boxOfficeRank: 19,	name: 'The Patriot', awards: ''},
        {boxOfficeRank: 20,	name: 'Chicken Run', awards: ''},
        {boxOfficeRank: 32,	name: 'Chocolat', awards: 'Best Picture Nominee'}
      ]
    }
  ];

  constructor() { }

  getMoviesByYear(year: string) {
    return this.movies.find(function(movie) {
      return year === movie.year;
    });
  }
}
